name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          working-directory: backend  # Move working-directory here

      - name: Install Dependencies
        run: npm ci

      - run: |
          touch .env
          echo "${{ secrets.MY_SECRET }}" > .env

      - name: Install PM2
        run: npm install -g pm2

      - run: pm2 restart index.js
